steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"

steps:
  - label: "Test Command"
    command: "ls -al"

steps:
  - label: "Run Tests"
    command: "gcloud config configuration list"